In [1]:
!pip install nltk

Collecting nltk
  Using cached nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in c:\users\saipr\anaconda3\envs\tensorflow_env\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\saipr\anaconda3\envs\tensorflow_env\lib\site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.6.28-cp310-cp310-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.68.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\users\saipr\anaconda3\envs\tensorflow_env\lib\site-packages (from click->nltk) (0.4.6)
Using cached nltk-3.9.4-py3-none-any.whl (1.6 MB)
Downloading regex-2026.6.28-cp310-cp310-win_amd64.whl (277 kB)
Downloading tqdm-4.68.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, regex, nltk

   ---------------------------------------- 0/3 [tqdm]
   ------------- -------------------------- 1/3 [regex]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   ---------------------------------------- 3/3 [nltk]

Successfully installed nltk-3.9.4 regex-2026.6.28 tqdm-4.68.3

In [1]:
import nltk

In [2]:
nltk.__version__

'3.9.4'

In [ ]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml

In [3]:
paragraph = "he is good boy. She is good girl"
paragraph

'he is good boy. She is good girl'

In [5]:
sentences = nltk.sent_tokenize(paragraph)
sentences

['he is good boy.', 'She is good girl']

In [6]:
words = nltk.word_tokenize(paragraph)
set(words)

{'.', 'She', 'boy', 'girl', 'good', 'he', 'is'}

In [7]:
from nltk.corpus import stopwords
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

Stemming :
bring the given word to the base word
o/p othe word may have may not be have meanning

In [14]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()
ps.stem('natural language processing')

'natural language process'

Lemmatization :
               bring the given word to base word
               o/p will be meaningful

In [17]:
from nltk.stem import WordNetLemmatizer
wn1 = WordNetLemmatizer()
wn1.lemmatize('natural language processing')

'natural language processing'

Text Cleaning
1. Remove Punctuation
2. Remove Stopwords
3. Stemming/ Lemmatization

In [23]:
import pandas as pd
df = pd.DataFrame({"in":["He is good boy", "She is good girl", "boy & girl are good"], "op":["P", "p", "N"]})

In [24]:
df

                    in op
0       He is good boy  P
1     She is good girl  p
2  boy & girl are good  N

In [25]:
corpus = []
import re
for i in range(len(df)):
    rp = re.sub('[^a-zA-Z]', " ",df["in"][i])
    rp = rp.lower()
    rp = rp.split()
    rp = [ps.stem(word) for word in rp if not word in stopwords.words('english')]
    rp = " ".join(rp)
    corpus.append(rp)

pd.DataFrame({"in":corpus})

              in
0       good boy
1      good girl
2  boy girl good

Vectorization--> Cout Vectorizer (Bag of Words) --> it counts the reition no.of wordds in the given sentece

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
pd.DataFrame(cv.fit_transform(corpus).toarray(),columns=cv.get_feature_names_out())

   boy  girl  good
0    1     0     1
1    0     1     1
2    1     1     1

TF-IDF Vectorizer-->
Term Frequecy(tf) ==> No.of time terms 't' occurs in document